# Copyright (C) 2004-2007 Prairie Games, Inc
# Please see LICENSE.TXT for details

## @defgroup defines defines
#  @ingroup world
#  The defines module provides enumeration and constants used throughout
#  mud.
#  @{

# If set to True the password will be sent by email only when registrating.
RPG_SECURE_REGISTRATION = True

RPG_BUILD_DEMO = False
RPG_BUILD_LIVE = False
RPG_BUILD_TESTING = False

def SetVersion(demo):
    global RPG_BUILD_DEMO
    RPG_BUILD_DEMO = demo

if RPG_BUILD_DEMO:
    RPG_BUILD_LIVE = True 
    RPG_CLIENT_VERSION = "Free 1.26"
else:
    RPG_CLIENT_VERSION = "Premium 1.26"
    if not RPG_BUILD_LIVE:
        RPG_CLIENT_VERSION = "Test Version"
        
RPG_BUILD_LIMITED = RPG_BUILD_DEMO

#debugging tool for remote server/client
PB_UNSAFE_TRACEBACKS = False

# Presence is the most important stat there is.
# To ensure that no player ever has an unfair advantage due to an exploit
# define max achievable presence here.
# This won't clamp any bonus the player might get due to items.
# - Don't forget to update on quest additions!
RPG_MAX_PRESENCE = 441


RPG_DMG_FIRE = 0
RPG_DMG_COLD = 1
RPG_DMG_POISON = 2
RPG_DMG_DISEASE = 3
RPG_DMG_ACID = 4
RPG_DMG_ELECTRICAL = 5
RPG_DMG_MAGICAL = 6
RPG_DMG_SLASHING = 7
RPG_DMG_IMPACT = 8
RPG_DMG_PIERCING = 9
RPG_DMG_CLEAVE = 10
RPG_DMG_PUMMEL = 11
RPG_DMG_PIERCING = 12
RPG_DMG_CLAWS = 13
RPG_DMG_CRITICAL = 14
RPG_DMG_PHYSICAL = 15
RPG_DMG_DRAIN = 16
RPG_DMG_UNSTOPPABLE = 17	# should never be resisted by anything
RPG_DMG_FOREST = 18
RPG_DMG_MINE = 19

RPG_RESIST_PHYSICAL = 0
RPG_RESIST_MAGICAL = 1
RPG_RESIST_FIRE = 2
RPG_RESIST_COLD = 3
RPG_RESIST_POISON = 4
RPG_RESIST_DISEASE = 5
RPG_RESIST_ACID = 6
RPG_RESIST_ELECTRICAL = 7
RPG_RESIST_UNSTOPPABLE = 8	# should never be resisted by anything
RPG_RESIST_FOREST = 9
RPG_RESIST_MINE = 10

RPG_RESIST_TEXT = {}
RPG_RESIST_TEXT[RPG_RESIST_PHYSICAL]="Physical"
RPG_RESIST_TEXT[RPG_RESIST_MAGICAL]="Magical"
RPG_RESIST_TEXT[RPG_RESIST_FIRE]="Fire"
RPG_RESIST_TEXT[RPG_RESIST_COLD]="Cold"
RPG_RESIST_TEXT[RPG_RESIST_POISON]="Poison"
RPG_RESIST_TEXT[RPG_RESIST_DISEASE]="Disease"
RPG_RESIST_TEXT[RPG_RESIST_ACID]="Acid"
RPG_RESIST_TEXT[RPG_RESIST_ELECTRICAL]="Electric"
RPG_RESIST_TEXT[RPG_RESIST_UNSTOPPABLE]="Unstoppable"	# should never be resisted by anything
RPG_RESIST_TEXT[RPG_RESIST_FOREST]="Foresting"
RPG_RESIST_TEXT[RPG_RESIST_MINE]="Mining"



DAMAGEFORRESIST = {}
DAMAGEFORRESIST[RPG_RESIST_PHYSICAL]=RPG_DMG_PHYSICAL
DAMAGEFORRESIST[RPG_RESIST_MAGICAL]=RPG_DMG_MAGICAL
DAMAGEFORRESIST[RPG_RESIST_FIRE]=RPG_DMG_FIRE
DAMAGEFORRESIST[RPG_RESIST_COLD]=RPG_DMG_COLD
DAMAGEFORRESIST[RPG_RESIST_POISON]=RPG_DMG_POISON
DAMAGEFORRESIST[RPG_RESIST_DISEASE]=RPG_DMG_DISEASE
DAMAGEFORRESIST[RPG_RESIST_ACID]=RPG_DMG_ACID
DAMAGEFORRESIST[RPG_RESIST_ELECTRICAL]=RPG_DMG_ELECTRICAL
DAMAGEFORRESIST[RPG_RESIST_UNSTOPPABLE]=RPG_DMG_UNSTOPPABLE	# should never be resisted by anything
DAMAGEFORRESIST[RPG_RESIST_FOREST]=RPG_DMG_FOREST
DAMAGEFORRESIST[RPG_RESIST_MINE]=RPG_DMG_MINE

RESISTFORDAMAGE = {}
RESISTFORDAMAGE[RPG_DMG_FIRE]=RPG_RESIST_FIRE
RESISTFORDAMAGE[RPG_DMG_COLD]=RPG_RESIST_COLD
RESISTFORDAMAGE[RPG_DMG_POISON]=RPG_RESIST_POISON
RESISTFORDAMAGE[RPG_DMG_DISEASE]=RPG_RESIST_DISEASE
RESISTFORDAMAGE[RPG_DMG_ACID]=RPG_RESIST_ACID
RESISTFORDAMAGE[RPG_DMG_ELECTRICAL]=RPG_RESIST_ELECTRICAL
RESISTFORDAMAGE[RPG_DMG_MAGICAL]=RPG_RESIST_MAGICAL
RESISTFORDAMAGE[RPG_DMG_SLASHING]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_IMPACT]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_PIERCING]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_CLEAVE]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_PUMMEL]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_PIERCING]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_CLAWS]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_CRITICAL]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_PHYSICAL]= RPG_RESIST_PHYSICAL
RESISTFORDAMAGE[RPG_DMG_DRAIN]=RPG_RESIST_MAGICAL
RESISTFORDAMAGE[RPG_DMG_UNSTOPPABLE]=RPG_RESIST_UNSTOPPABLE	# should never be resisted by anything
RESISTFORDAMAGE[RPG_DMG_FOREST]=RPG_RESIST_FOREST
RESISTFORDAMAGE[RPG_DMG_MINE]=RPG_RESIST_MINE

RPG_MSG_SPEECH_WORLD = 0
RPG_MSG_SPEECH_ZONE = 1
RPG_MSG_SPEECH_PARTY = 2
RPG_MSG_SPEECH_SAY = 3
RPG_MSG_SPEECH_AUCTION = 4
RPG_MSG_SPEECH_GLOBAL = 5
RPG_MSG_SPEECH_ALLIANCE = 6
RPG_MSG_SPEECH_SYSTEM = 7
RPG_MSG_SPEECH_TELL = 8
RPG_MSG_SPEECH_TOLD = 9
RPG_MSG_SPEECH_EMOTE = 10
RPG_MSG_SPEECH_OT = 11
RPG_MSG_SPEECH_HELP = 12
RPG_MSG_SPEECH_PLAYERJOINED = 13
RPG_MSG_SPEECH_GUILD = 14
RPG_MSG_SPEECH_ERROR = 15


RPG_MSG_GAME_GLOBAL = 0
RPG_MSG_GAME_COMBAT = 1 #generic combat
RPG_MSG_GAME_COMBAT_HIT = 2 #player's char hit somone
RPG_MSG_GAME_COMBAT_GOTHIT = 3 #player's char got hit
RPG_MSG_GAME_CASTING = 4 #player's char got hit
RPG_MSG_GAME_SPELLBEGIN = 5 #player's char got hit
RPG_MSG_GAME_SPELLEND = 6 #player's char got hit
RPG_MSG_GAME_DENIED = 7
RPG_MSG_GAME_GAINED = 8
RPG_MSG_GAME_LOST = 9
RPG_MSG_GAME_LOOT = 10
RPG_MSG_GAME_LEVELGAINED = 11
RPG_MSG_GAME_LEVELLOST = 12
RPG_MSG_GAME_CHARDEATH = 13
RPG_MSG_GAME_PARTYDEATH = 14
RPG_MSG_GAME_GOOD = 15
RPG_MSG_GAME_BAD = 16
RPG_MSG_GAME_EVENT = 17
RPG_MSG_GAME_GREEN = 18
RPG_MSG_GAME_BLUE = 19
RPG_MSG_GAME_WHITE = 20
RPG_MSG_GAME_YELLOW = 21
RPG_MSG_GAME_RED = 22
RPG_MSG_GAME_NPC_SPEECH = 23
RPG_MSG_GAME_PET_SPEECH = 24
RPG_MSG_GAME_CASTING_NPC = 25  # Non-player character begins casting a spell

RPG_FREQ_ALWAYS     = 1
RPG_FREQ_COMMON     = 3
RPG_FREQ_UNCOMMON   = 5
RPG_FREQ_RARE       = 10
RPG_FREQ_VERYRARE   = 25
RPG_FREQ_ULTRARARE  = 35
RPG_FREQ_IMPOSSIBLE = 50

RPG_FREQ_TEXT = {}
RPG_FREQ_TEXT[RPG_FREQ_ALWAYS]="Always"
RPG_FREQ_TEXT[RPG_FREQ_COMMON]="Common"
RPG_FREQ_TEXT[RPG_FREQ_UNCOMMON]="Uncommon"
RPG_FREQ_TEXT[RPG_FREQ_RARE]="Rare"
RPG_FREQ_TEXT[RPG_FREQ_VERYRARE]="Very Rare"
RPG_FREQ_TEXT[RPG_FREQ_ULTRARARE]="Ultra Rare"
RPG_FREQ_TEXT[RPG_FREQ_IMPOSSIBLE]="Impossible"


RPG_QUALITY_CRUDDY      = 0
RPG_QUALITY_SHODDY      = 1
RPG_QUALITY_NORMAL      = 2
RPG_QUALITY_SUPERIOR    = 3
RPG_QUALITY_EXCEPTIONAL = 4

RPG_QUALITY_TEXT = {}
RPG_QUALITY_TEXT[RPG_QUALITY_CRUDDY]="Cruddy"
RPG_QUALITY_TEXT[RPG_QUALITY_SHODDY]="Shoddy"
RPG_QUALITY_TEXT[RPG_QUALITY_NORMAL]="Normal"
RPG_QUALITY_TEXT[RPG_QUALITY_SUPERIOR]="Superior"
RPG_QUALITY_TEXT[RPG_QUALITY_EXCEPTIONAL]="Exceptional"

RPG_QUALITY_MODS = {}
RPG_QUALITY_MODS[RPG_QUALITY_CRUDDY]=.4
RPG_QUALITY_MODS[RPG_QUALITY_SHODDY]=.5
RPG_QUALITY_MODS[RPG_QUALITY_NORMAL]=.6
RPG_QUALITY_MODS[RPG_QUALITY_SUPERIOR]=.8
RPG_QUALITY_MODS[RPG_QUALITY_EXCEPTIONAL]=1.0


# spell types
RPG_SPELL_NOSPECIAL  = 0
RPG_SPELL_HEALING    = 1
RPG_SPELL_HARMFUL    = 1 << 1
RPG_SPELL_AICAST     = 1 << 2  # mobs are allowed to use this spell
RPG_SPELL_PERSISTENT = 1 << 3  # spell effect persists over logout
RPG_SPELL_NOAGGRO    = 1 << 4  # spell won't produce aggro


# Soulbound items cannot be traded
RPG_ITEM_SOULBOUND = 1 << 0
# Only one unique item of a given type can be equipped simultaneously
RPG_ITEM_UNIQUE  = 1 << 1
# Ethereal items get destroyed when a player leaves the game
RPG_ITEM_ETHEREAL = 1 << 2
# Indestructible items don't need repair
RPG_ITEM_INDESTRUCTIBLE = 1 << 3
# Artifacts don't have quality applied, etc
RPG_ITEM_ARTIFACT = 1 << 4
# Flag for a player enchanted item
RPG_ITEM_ENCHANTED = 1 << 5
# Premium items can only be used with a premium account
RPG_ITEM_PREMIUM = 1 << 6
# Only one item of this kind exists in the whole world of Mirth - to be implemented
RPG_ITEM_WORLDUNIQUE = 1 << 7
# Literature items (Scrolls, Books, Tomes) sell only for 1/10 of what they're bought at
#  further uses in the future...
RPG_ITEM_LITERATURE = 1 << 8
# Quest items are inexpungeable.
RPG_ITEM_QUEST = 1 << 9

#will be set if item has dimished abilities based on owner's level
#use penalty
#RPG_ITEM_DIMINISHED = 1 << 5

# Flags on how to check for requirements on items.
# Nothing special.
RPG_ITEMREQUIREMENT_NORMAL = 0
# Instead of checking if the character matches itemProto.requiredClassNum class
#  requirements, check if the character has itemProto.requiredClassNum classes
#  at all. Useful to restricting items to single-classed characters.
RPG_ITEMREQUIREMENT_EXACTCLASSNUM = 1
# When checking required races, see that the character is of none of the listed.
RPG_ITEMREQUIREMENT_RACEREVERSED = 1 << 1
# When checking required classes, see that the character has none of the listed.
RPG_ITEMREQUIREMENT_CLASSREVERSED = 1 << 2

RPG_LOOT_PICKPOCKET = 1    # enable pick pocketing on a loot-table item (comes even before coins)


RPG_ITEM_FLAG_TEXT = {}
RPG_ITEM_FLAG_TEXT[RPG_ITEM_SOULBOUND] = "SOULBOUND"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_UNIQUE] = "UNIQUE"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_ETHEREAL] = "ETHEREAL"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_INDESTRUCTIBLE] = "INDESTRUCTIBLE"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_ARTIFACT] = "ARTIFACT"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_ENCHANTED] = "ENCHANTED"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_PREMIUM] = "PREMIUM"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_WORLDUNIQUE] = "WORLD UNIQUE"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_LITERATURE] = "LITERATURE"
RPG_ITEM_FLAG_TEXT[RPG_ITEM_QUEST] = "QUEST"

RPG_ITEM_TRIGGER_WORN = 0 #chance per tick for just being worn, check is every 30 seconds
RPG_ITEM_TRIGGER_MELEE = 1 #chance of proc on melee strike
RPG_ITEM_TRIGGER_DAMAGED = 2 #chace of proc when user is damaged
RPG_ITEM_TRIGGER_USE = 3 #when used (possibly limited by charges)
RPG_ITEM_TRIGGER_POISON = 4 #applied poison

RPG_ITEMPROC_MAX = 2    # maximum of possible temporary procs active on a single weapon (e.g. poisons, enchantments)
RPG_ITEMPROC_POISON = 0
RPG_ITEMPROC_ENCHANTMENT = 1

RPG_ITEMSET_TEST_LESSEQUAL = 0	# less or equal the amount of items specified are necessary for the power to become active
RPG_ITEMSET_TEST_EQUAL = 1	# exactly the specified amount of items are required for the power to become active
RPG_ITEMSET_TEST_GREATEREQUAL = 2	# more or equal the amount of specified items are needed for the power to become active

RPG_EFFECT_STAGE_GLOBAL = 0
RPG_EFFECT_STAGE_BEGIN = 1
RPG_EFFECT_STAGE_TICK = 2
RPG_EFFECT_STAGE_END = 3

RPG_EFFECT_WATERBREATHING = 1
RPG_EFFECT_LEVITATE = 1 << 1
RPG_EFFECT_PARALYSIS = 1 << 2
RPG_EFFECT_ROOT = 1 << 3
RPG_EFFECT_RESURRECTION = 1 << 4
RPG_EFFECT_STUN = 1 << 5
RPG_EFFECT_SLEEP = 1 << 6
RPG_EFFECT_CHARM = 1 << 7
RPG_EFFECT_INTERRUPT = 1 << 8
RPG_EFFECT_BANISH = 1 << 9
RPG_EFFECT_SUMMONMONSTER = 1 << 10
RPG_EFFECT_SUMMONALLY = 1 << 11

RPG_MONEY_TIN = 0
RPG_MONEY_COPPER = 1
RPG_MONEY_SILVER = 2
RPG_MONEY_GOLD = 3
RPG_MONEY_PLATINUM = 4


RPG_SLOT_HEAD = 0
RPG_SLOT_LEAR = 1
RPG_SLOT_REAR = 2
RPG_SLOT_NECK = 3
RPG_SLOT_SHOULDERS = 4
RPG_SLOT_BACK = 5
RPG_SLOT_CHEST = 6 
RPG_SLOT_ARMS = 7
RPG_SLOT_HANDS = 8
RPG_SLOT_LFINGER = 9 
RPG_SLOT_RFINGER = 10
RPG_SLOT_PRIMARY = 11
RPG_SLOT_SECONDARY = 12
RPG_SLOT_RANGED = 13
RPG_SLOT_AMMO = 14
RPG_SLOT_WAIST= 15 
RPG_SLOT_LEGS = 16
RPG_SLOT_FEET = 17
RPG_SLOT_LWRIST = 18
RPG_SLOT_RWRIST = 19
RPG_SLOT_SHIELD = 20
RPG_SLOT_LIGHT = 21

RPG_SLOT_CARRY0 = 22
RPG_SLOT_CARRY1 = 23
RPG_SLOT_CARRY2 = 24
RPG_SLOT_CARRY3 = 25
RPG_SLOT_CARRY4 = 26
RPG_SLOT_CARRY5 = 27
RPG_SLOT_CARRY6 = 28
RPG_SLOT_CARRY7 = 29
RPG_SLOT_CARRY8 = 30
RPG_SLOT_CARRY9 = 31
RPG_SLOT_CARRY10 = 32
RPG_SLOT_CARRY11 = 33
RPG_SLOT_CARRY12 = 34
RPG_SLOT_CARRY13 = 35
RPG_SLOT_CARRY14 = 36
RPG_SLOT_CARRY15 = 37
RPG_SLOT_CARRY16 = 38
RPG_SLOT_CARRY17 = 39
RPG_SLOT_CARRY18 = 40
RPG_SLOT_CARRY19 = 41
RPG_SLOT_CARRY20 = 42
RPG_SLOT_CARRY21 = 43
RPG_SLOT_CARRY22 = 44
RPG_SLOT_CARRY23 = 45
RPG_SLOT_CARRY24 = 46
RPG_SLOT_CARRY25 = 47
RPG_SLOT_CARRY26 = 48
RPG_SLOT_CARRY27 = 49
RPG_SLOT_CARRY28 = 50
RPG_SLOT_CARRY29 = 51
RPG_SLOT_CARRY30 = 52
RPG_SLOT_CARRY31 = 53
RPG_SLOT_CARRY32 = 54
RPG_SLOT_CARRY33 = 55
RPG_SLOT_CARRY34 = 56
RPG_SLOT_CARRY35 = 57
RPG_SLOT_CARRY36 = 58
RPG_SLOT_CARRY37 = 59
RPG_SLOT_CARRY38 = 60
RPG_SLOT_CARRY39 = 61
RPG_SLOT_CARRY40 = 62 
RPG_SLOT_CARRY41 = 63
RPG_SLOT_CARRY42 = 64
RPG_SLOT_CARRY43 = 65
RPG_SLOT_CARRY44 = 66
RPG_SLOT_CARRY45 = 67
RPG_SLOT_CARRY46 = 68
RPG_SLOT_CARRY47 = 69
RPG_SLOT_CARRY48 = 70
RPG_SLOT_CARRY49 = 71
RPG_SLOT_CARRY50 = 72
RPG_SLOT_CARRY51 = 73
RPG_SLOT_CARRY52 = 74
RPG_SLOT_CARRY53 = 75
RPG_SLOT_CARRY54 = 76
RPG_SLOT_CARRY55 = 77
RPG_SLOT_CARRY56 = 78
RPG_SLOT_CARRY57 = 79
RPG_SLOT_CARRY58 = 80
RPG_SLOT_CARRY59 = 81
RPG_SLOT_TRADE0 = 82
RPG_SLOT_TRADE1 = 83
RPG_SLOT_TRADE2 = 84
RPG_SLOT_TRADE3 = 85
RPG_SLOT_TRADE4 = 86
RPG_SLOT_TRADE5 = 87
RPG_SLOT_TRADE6 = 88
RPG_SLOT_TRADE7 = 89
RPG_SLOT_TRADE8 = 90
RPG_SLOT_TRADE9 = 91
RPG_SLOT_TRADE10 = 92
RPG_SLOT_TRADE11 = 93
RPG_SLOT_UNUSED = 94
RPG_SLOT_UNUSED = 95
RPG_SLOT_UNUSED = 96
RPG_SLOT_UNUSED = 97
RPG_SLOT_LOOT0 = 98
RPG_SLOT_LOOT1 = 99
RPG_SLOT_LOOT2 = 100
RPG_SLOT_LOOT3 = 101
RPG_SLOT_LOOT4 = 102
RPG_SLOT_LOOT5 = 103
RPG_SLOT_LOOT6 = 104
RPG_SLOT_LOOT7 = 105
RPG_SLOT_LOOT8 = 106
RPG_SLOT_LOOT9 = 107
RPG_SLOT_CURSOR = 138

RPG_SLOT_PET_HEAD = 140
RPG_SLOT_PET_LEAR = 141
RPG_SLOT_PET_REAR = 142
RPG_SLOT_PET_NECK = 143
RPG_SLOT_PET_SHOULDERS = 144
RPG_SLOT_PET_BACK =145
RPG_SLOT_PET_CHEST = 146 
RPG_SLOT_PET_ARMS = 147
RPG_SLOT_PET_HANDS = 148
RPG_SLOT_PET_LFINGER = 149 
RPG_SLOT_PET_RFINGER = 150
RPG_SLOT_PET_PRIMARY = 151
RPG_SLOT_PET_SECONDARY = 152
RPG_SLOT_PET_RANGED = 153
RPG_SLOT_PET_AMMO = 154
RPG_SLOT_PET_WAIST= 155 
RPG_SLOT_PET_LEGS = 156
RPG_SLOT_PET_FEET = 157
RPG_SLOT_PET_LWRIST = 158
RPG_SLOT_PET_RWRIST = 159
RPG_SLOT_PET_SHIELD = 160
RPG_SLOT_PET_LIGHT = 161

RPG_SLOT_CRAFTING0 = 162
RPG_SLOT_CRAFTING1 = 163
RPG_SLOT_CRAFTING2 = 164
RPG_SLOT_CRAFTING3 = 165
RPG_SLOT_CRAFTING4 = 166
RPG_SLOT_CRAFTING5 = 167
RPG_SLOT_CRAFTING6 = 168
RPG_SLOT_CRAFTING7 = 169
RPG_SLOT_CRAFTING8 = 170
RPG_SLOT_CRAFTING9 = 171
RPG_SLOT_CRAFTING10 = 172
RPG_SLOT_CRAFTING11 = 173
RPG_SLOT_CRAFTING12 = 174
RPG_SLOT_CRAFTING13 = 175
RPG_SLOT_CRAFTING14 = 176
RPG_SLOT_CRAFTING15 = 177

RPG_SLOT_MAX = 177



RPG_SLOT_TEXT = {}
RPG_SLOT_TEXT[RPG_SLOT_HEAD]="Head"
RPG_SLOT_TEXT[RPG_SLOT_LEAR]="Ear"
RPG_SLOT_TEXT[RPG_SLOT_REAR]="Ear"
RPG_SLOT_TEXT[RPG_SLOT_NECK]="Neck"
RPG_SLOT_TEXT[RPG_SLOT_SHOULDERS]="Shoulders"
RPG_SLOT_TEXT[RPG_SLOT_BACK]="Back"
RPG_SLOT_TEXT[RPG_SLOT_CHEST]="Chest"
RPG_SLOT_TEXT[RPG_SLOT_ARMS]="Arms"
RPG_SLOT_TEXT[RPG_SLOT_HANDS]="Hands"
RPG_SLOT_TEXT[RPG_SLOT_LFINGER]="Finger"
RPG_SLOT_TEXT[RPG_SLOT_RFINGER]="Finger"
RPG_SLOT_TEXT[RPG_SLOT_PRIMARY]="Primary"
RPG_SLOT_TEXT[RPG_SLOT_SECONDARY]="Offhand"
RPG_SLOT_TEXT[RPG_SLOT_RANGED]="Ranged"
RPG_SLOT_TEXT[RPG_SLOT_AMMO]="Ammo"
RPG_SLOT_TEXT[RPG_SLOT_WAIST]="Waist"
RPG_SLOT_TEXT[RPG_SLOT_LEGS]="Legs"
RPG_SLOT_TEXT[RPG_SLOT_FEET]="Feet"
RPG_SLOT_TEXT[RPG_SLOT_LWRIST]="Wrist"
RPG_SLOT_TEXT[RPG_SLOT_RWRIST]="Wrist"
RPG_SLOT_TEXT[RPG_SLOT_SHIELD]="Shield"
RPG_SLOT_TEXT[RPG_SLOT_LIGHT]="Light"


RPG_SLOT_CRAFTING_BEGIN=RPG_SLOT_CRAFTING0
RPG_SLOT_CRAFTING_END=RPG_SLOT_CRAFTING15+1


RPG_SLOT_WORN_BEGIN=RPG_SLOT_HEAD
RPG_SLOT_WORN_END=RPG_SLOT_CARRY0

RPG_SLOT_PET_BEGIN=RPG_SLOT_PET_HEAD
RPG_SLOT_PET_END=RPG_SLOT_PET_LIGHT+1


RPG_SLOT_TRADE_BEGIN=RPG_SLOT_TRADE0
RPG_SLOT_TRADE_END=RPG_SLOT_TRADE11+1


RPG_SLOT_CARRY_BEGIN=RPG_SLOT_CARRY0
RPG_SLOT_CARRY_END=RPG_SLOT_TRADE0

RPG_SLOT_LOOT_BEGIN=RPG_SLOT_LOOT0
RPG_SLOT_LOOT_END=RPG_SLOT_LOOT0+17


#players
RPG_SLOT_BANK_BEGIN=1000
RPG_SLOT_BANK_END=1080



RPG_TARGET_SELF = 0
RPG_TARGET_PET = 1
RPG_TARGET_OTHER = 2
RPG_TARGET_PARTY = 3
RPG_TARGET_ALLIANCE = 4

RPG_TARGET_TEXT = {}
RPG_TARGET_TEXT[RPG_TARGET_SELF]="Self"
RPG_TARGET_TEXT[RPG_TARGET_PET]="Pet"
RPG_TARGET_TEXT[RPG_TARGET_OTHER]="Individual"
RPG_TARGET_TEXT[RPG_TARGET_PARTY]="Party"
RPG_TARGET_TEXT[RPG_TARGET_ALLIANCE]="Alliance"

RPG_PET_FOLLOWME  = 0
RPG_PET_GUARDSPOT = 1 #aggro range, something
RPG_PET_STAY = 2 #aggro range 0
RPG_PLAYERPET_AGGROTHRESHOLD = 50  # scales with pet level


RPG_SPAWN_NOASSIST = 1  # doesn't run to aid of associates
RPG_SPAWN_UNIQUE = 1 << 1  # only one up in zone at a time, properly named
RPG_SPAWN_NOCORPSE = 1 << 2  # leave no corpse upon death
RPG_SPAWN_BANKER = 1 << 3
RPG_SPAWN_INN = 1 << 4
# If set, don't reward experience when this spawn gets killed.
RPG_SPAWN_NOXP = 1 << 5
# If set, never randomize the sex of this spawn. Useful for non-uniques.
RPG_SPAWN_FIXEDSEX = 1 << 6
# Attack anything and all, regardless realm or factions if the target is a player.
RPG_SPAWN_AGGRESSIVE = 1 << 7
# Never generate aggro based on realm or factions, only when provoked.
RPG_SPAWN_PASSIVE = 1 << 8
# Don't generate any random loot at all.
RPG_SPAWN_NORANDOMLOOT = 1 << 9
RPG_SPAWN_RESOURCE = 1 << 10
# Player monster received template advancement points if set.
# Exists so old monsters can be given their missing advancement
#  points as well, won't interfere with anything :-)
RPG_SPAWN_MONSTERADVANCED = 1 << 30

# Definitions on how to choose next spawngroup if previous needs replacing.
# Chooses a completely random spawngroup out of controlled spawngroups
RPG_SPAWNCONTROLLER_CYCLE_RANDOM = 0
# Chooses a random spawngroup out of controlled spawngroups, but makes
#  sure a different than the previous one is chosen (unless only one
#  group is controlled)
RPG_SPAWNCONTROLLER_CYCLE_OTHER = 1
# Chooses a random spawngroup out of controlled spawngroups, but tries
#  to choose a different realm than last one.
RPG_SPAWNCONTROLLER_CYCLE_REALM = 2
# Attempt to choose a spawngroup with the same realm as the killer of the
#  last spawn under control. If no such group is found, try to cycle like
#  RPG_SPAWNCONTROLLER_CYCLE_REALM.
RPG_SPAWNCONTROLLER_CYCLE_LASTKILLERREALM = 3
# Attempt to choose a spawngroup with the same realm as had the most killers
#  of the previously controlled spawngroups mobs. If this is not possible, cycle
#  like RPG_SPAWNCONTROLLER_CYCLE_REALM.
RPG_SPAWNCONTROLLER_CYCLE_KILLERREALM = 4

# Different flags that further control spawn group respawns.
# Normal respawning, like other spawnpoints, just trigger on cycle conditions.
RPG_SPAWNCONTROLLER_RESPAWN_NORMAL = 0
# Prevent respawning until all current spawns have been killed once.
RPG_SPAWNCONTROLLER_RESPAWN_WIPE = 1
# Immediately respawn mobs at all linked spawnpoints on cycling.
RPG_SPAWNCONTROLLER_RESPAWN_IMMEDIATE = 1 << 1


RPG_CLIMATE_TROPICAL = 0
RPG_CLIMATE_DRY = 1
RPG_CLIMATE_TEMPERATE = 2
RPG_CLIMATE_COLD = 3
RPG_CLIMATE_POLAR = 4

RPG_DIFFICULTY_EASY = 0
RPG_DIFFICULTY_NORMAL = 1
RPG_DIFFICULTY_HARDCORE = 2

RPG_FACTION_HATED = -250
RPG_FACTION_DISLIKED = -50
RPG_FACTION_UNDECIDED = 0
RPG_FACTION_LIKED = 100
RPG_FACTION_ADORED = 500

# Bane damage follows the formula 0.05 + 0.95 * index^2 / 76
RPG_BANEWEAPON_DAMAGE = {}
RPG_BANEWEAPON_DAMAGE[0] = 0.05
RPG_BANEWEAPON_DAMAGE[1] = 0.06
RPG_BANEWEAPON_DAMAGE[2] = 0.10
RPG_BANEWEAPON_DAMAGE[3] = 0.16
RPG_BANEWEAPON_DAMAGE[4] = 0.25
RPG_BANEWEAPON_DAMAGE[5] = 0.36
RPG_BANEWEAPON_DAMAGE[6] = 0.50
RPG_BANEWEAPON_DAMAGE[7] = 0.66
RPG_BANEWEAPON_DAMAGE[8] = 0.85
RPG_BANEWEAPON_DAMAGE[9] = 1.06
RPG_BANEWEAPON_DAMAGE[10] = 1.30
RPG_BANEWEAPON_DAMAGE[11] = 1.56
RPG_BANEWEAPON_DAMAGE[12] = 1.85

# Bane offense follows the formula 0.05 + 0.95 * index^2 / 144
RPG_BANEWEAPON_OFFENSE = {}
RPG_BANEWEAPON_OFFENSE[0] = 0.05
RPG_BANEWEAPON_OFFENSE[1] = 0.06
RPG_BANEWEAPON_OFFENSE[2] = 0.08
RPG_BANEWEAPON_OFFENSE[3] = 0.11
RPG_BANEWEAPON_OFFENSE[4] = 0.16
RPG_BANEWEAPON_OFFENSE[5] = 0.21
RPG_BANEWEAPON_OFFENSE[6] = 0.29
RPG_BANEWEAPON_OFFENSE[7] = 0.37
RPG_BANEWEAPON_OFFENSE[8] = 0.47
RPG_BANEWEAPON_OFFENSE[9] = 0.58
RPG_BANEWEAPON_OFFENSE[10] = 0.71
RPG_BANEWEAPON_OFFENSE[11] = 0.85
RPG_BANEWEAPON_OFFENSE[12] = 1.00

RPG_DIALOG_REQUIREMENT_EXCLUSIVE_CLASSES = 1
RPG_DIALOG_REQUIREMENT_EXCLUSIVE_RACES = 1 << 1
RPG_DIALOG_REQUIREMENT_EXCLUSIVE_REALMS = 1 << 2
RPG_DIALOG_REQUIREMENT_EXCLUSIVE_SKILLS = 1 << 3
RPG_DIALOG_REQUIREMENT_EXCLUSIVE_ITEMS = 1 << 4

RPG_REALM_UNDEFINED = -1
RPG_REALM_NEUTRAL = 0
RPG_REALM_LIGHT = 1
RPG_REALM_DARKNESS = 2
RPG_REALM_MONSTER = 3
RPG_REALM_DEFAULT = RPG_REALM_LIGHT

RPG_REALM_TEXT = {
    RPG_REALM_UNDEFINED: "Undefined",
    RPG_REALM_NEUTRAL: "Neutral",
    RPG_REALM_LIGHT: "Fellowship of Light",
    RPG_REALM_DARKNESS: "Minions of Darkness",
    RPG_REALM_MONSTER: "Monster Realm"
}


RPG_CLASS_ABBR = {}
RPG_CLASS_ABBR["Necromancer"]="NEC"
RPG_CLASS_ABBR["Wizard"]="WIZ"
RPG_CLASS_ABBR["Cleric"]="CLR"
RPG_CLASS_ABBR["Warrior"]="WAR"
RPG_CLASS_ABBR["Barbarian"]="BAR"
RPG_CLASS_ABBR["Tempest"]="TMP"
RPG_CLASS_ABBR["Shaman"]="SHM"
RPG_CLASS_ABBR["Assassin"]="ASN"
RPG_CLASS_ABBR["Revealer"]="REV"
RPG_CLASS_ABBR["Thief"]="THF"
RPG_CLASS_ABBR["Doom Knight"]="DMK"
RPG_CLASS_ABBR["Druid"]="DRD"
RPG_CLASS_ABBR["Paladin"]="PAL"
RPG_CLASS_ABBR["Monk"]="MNK"
RPG_CLASS_ABBR["Bard"]="BRD"
RPG_CLASS_ABBR["Ranger"]="RNG"

RPG_ARCHETYPE_ABBR = {}
RPG_ARCHETYPE_ABBR["Necromancer"]="MGE"
RPG_ARCHETYPE_ABBR["Wizard"]="MGE"
RPG_ARCHETYPE_ABBR["Cleric"]="PRT"
RPG_ARCHETYPE_ABBR["Warrior"]="CMT"
RPG_ARCHETYPE_ABBR["Barbarian"]="CMT"
RPG_ARCHETYPE_ABBR["Tempest"]="PRT"
RPG_ARCHETYPE_ABBR["Shaman"]="PRT"
RPG_ARCHETYPE_ABBR["Assassin"]="RGE"
RPG_ARCHETYPE_ABBR["Revealer"]="MGE"
RPG_ARCHETYPE_ABBR["Thief"]="RGE"
RPG_ARCHETYPE_ABBR["Doom Knight"]="CMT"
RPG_ARCHETYPE_ABBR["Druid"]="PRT"
RPG_ARCHETYPE_ABBR["Paladin"]="CMT"
RPG_ARCHETYPE_ABBR["Monk"]="CMT"
RPG_ARCHETYPE_ABBR["Bard"]="RGE"
RPG_ARCHETYPE_ABBR["Ranger"]="CMT"

RPG_REALM_RACES = {}
RPG_REALM_RACES[RPG_REALM_LIGHT] = ["Human","Gnome","Elf","Halfling","Dwarf","Titan","Drakken"]
RPG_REALM_RACES[RPG_REALM_DARKNESS] = ["Human","Gnome","Troll","Ogre","Drakken","Orc","Goblin","Dark Elf"]

RPG_REALM_CLASSES = {}
RPG_REALM_DARKNESS_CLASSES =["Necromancer","Wizard","Cleric","Warrior","Barbarian","Tempest","Shaman","Assassin","Revealer","Thief","Doom Knight","Druid"]
RPG_REALM_LIGHT_CLASSES =["Shaman","Warrior","Paladin","Cleric","Tempest","Wizard","Monk","Barbarian","Thief","Druid","Bard","Ranger","Revealer"]

RPG_REALM_CLASSES[RPG_REALM_LIGHT]=RPG_REALM_LIGHT_CLASSES
RPG_REALM_CLASSES[RPG_REALM_DARKNESS]=RPG_REALM_DARKNESS_CLASSES

RPG_RACE_CLASSES = {}
RPG_RACE_CLASSES["Human"]=["Paladin","Cleric","Necromancer","Tempest","Wizard","Shaman","Monk","Barbarian","Warrior","Assassin","Revealer","Druid","Ranger","Bard","Thief","Doom Knight"]
RPG_RACE_CLASSES["Gnome"]=["Necromancer","Wizard","Assassin","Revealer","Thief","Monk","Tempest","Cleric"]
RPG_RACE_CLASSES["Halfling"]=["Paladin","Cleric","Shaman","Warrior","Druid","Ranger","Bard","Thief","Monk","Tempest","Wizard"]
RPG_RACE_CLASSES["Elf"]=["Paladin","Cleric","Tempest","Wizard","Shaman","Monk","Warrior","Druid","Ranger","Bard","Revealer"]
RPG_RACE_CLASSES["Dwarf"]=["Paladin","Cleric","Barbarian","Warrior","Shaman","Tempest","Revealer"]
RPG_RACE_CLASSES["Titan"]=["Paladin","Cleric","Tempest","Wizard","Monk","Warrior","Ranger"]

RPG_RACE_CLASSES["Drakken"]=["Cleric","Necromancer","Tempest","Wizard","Shaman","Barbarian","Warrior","Assassin","Revealer","Thief","Doom Knight","Monk","Ranger"]
RPG_RACE_CLASSES["Dark Elf"]=["Cleric","Necromancer","Tempest","Wizard","Shaman","Barbarian","Warrior","Assassin","Revealer","Thief","Doom Knight","Druid"]
RPG_RACE_CLASSES["Troll"]=["Monk","Barbarian","Warrior","Doom Knight","Shaman"]
RPG_RACE_CLASSES["Orc"]=["Cleric","Necromancer","Tempest","Wizard","Shaman","Barbarian","Warrior","Assassin","Revealer","Thief","Doom Knight","Druid"]
RPG_RACE_CLASSES["Goblin"]=["Cleric","Necromancer","Tempest","Wizard","Shaman","Barbarian","Warrior","Assassin","Revealer","Thief","Druid"]
RPG_RACE_CLASSES["Ogre"]=["Cleric","Tempest","Shaman","Barbarian","Warrior","Assassin","Doom Knight","Druid"]


class RaceStats:
    def __init__(self,str,bdy,ref,agi,dex,mnd,wis,mys):
        self.STR = str
        self.BDY = bdy
        self.REF = ref
        self.AGI = agi
        self.DEX = dex
        self.MND = mnd
        self.WIS = wis
        self.MYS = mys
        

RPG_STATS = ("STR","BDY","REF","AGI","DEX","MND","WIS","MYS")
RPG_STAT_PERCENTLOOKUP = ("haste","move","swimMove","slow","flying",
    "dmgBonusPrimary","dmgBonusOffhand","meleeDmgMod","critical","castHaste",
    "innateHaste","castHealMod","castDmgMod","aggroRange","size","regenCombat",
    "visibility","seeInvisible","sneak")
RPG_DERIVEDSTATS = ("maxHealth","maxMana","maxStamina","offense","defense",
    "primaryAttackRate","secondaryAttackRate","critical")
RPG_RESISTSTATS = ("resistPhysical","resistMagical","resistAcid","resistElectrical","resistDisease","resistFire","resistCold","resistPoison")
RPG_RESISTLOOKUP = {"resistPhysical":RPG_RESIST_PHYSICAL,"resistMagical":RPG_RESIST_MAGICAL,"resistAcid":RPG_RESIST_ACID,"resistElectrical":RPG_RESIST_ELECTRICAL,
"resistDisease":RPG_RESIST_DISEASE,"resistFire":RPG_RESIST_FIRE,"resistCold":RPG_RESIST_COLD,"resistPoison":RPG_RESIST_POISON}
RPG_RESISTVALUES = (RPG_RESIST_COLD,RPG_RESIST_FIRE,RPG_RESIST_DISEASE,RPG_RESIST_MAGICAL,RPG_RESIST_PHYSICAL,RPG_RESIST_POISON,RPG_RESIST_ELECTRICAL,RPG_RESIST_ACID)

RPG_RACE_STATS={}
RPG_RACE_STATS['Human']=RaceStats(90,90,90,90,90,90,90,90) 
RPG_RACE_STATS['Halfling']=RaceStats(80,80,115,115,115,75,90,50) 
RPG_RACE_STATS['Dwarf']=RaceStats(110,115,75,75,75,70,110,90) 
RPG_RACE_STATS['Elf']=RaceStats(80,60,100,90,100,110,100,110) 
RPG_RACE_STATS['Gnome']=RaceStats(75,80,105,110,110,110,120,50) 
RPG_RACE_STATS['Titan']=RaceStats(125,110,80,70,70,80,80,110)

RPG_RACE_STATS['Troll']=RaceStats(120,110,70,70,70,50,30,5) 
RPG_RACE_STATS['Dark Elf']=RaceStats(85,60,115,105,110,110,80,100) 
RPG_RACE_STATS['Ogre']=RaceStats(115,100,70,70,70,80,90,90) 
RPG_RACE_STATS['Goblin']=RaceStats(90,100,95,95,90,120,80,100) 
RPG_RACE_STATS['Orc']=RaceStats(85,115,95,85,90,85,85,85) 
RPG_RACE_STATS['Drakken']=RaceStats(100,100,100,100,100,90,80,85)

# default distribution of starting stats, one list must sum up to 100
RPG_DEFAULT_STATS = {
"Warrior":(40,35,10,5,10,0,0,0),
"Assassin":(10,10,10,30,40,0,0,0),
"Thief":(10,10,10,30,40,0,0,0),
"Doom Knight":(40,35,10,0,0,15,0,0),
"Paladin":(40,35,10,0,0,0,15,0),
"Bard":(30,35,10,0,0,25,0,0),
"Barbarian":(35,40,15,0,10,0,0,0),
"Ranger":(25,25,20,5,25,0,0,0),
"Monk":(30,20,20,20,10,0,0,0),
"Cleric":(10,25,5,0,10,0,50,0),
"Wizard":(10,25,5,0,10,50,0,0),
"Revealer":(10,25,5,0,10,50,0,0),
"Necromancer":(10,25,5,0,10,50,0,0),
"Tempest":(10,25,5,0,10,0,0,50),
"Druid":(10,25,5,0,10,0,50,0),
"Shaman":(10,25,5,0,10,0,0,50),
}

RPG_PC_RACES = ("Human","Gnome","Dwarf","Halfling","Elf","Ogre","Drakken","Troll","Orc","Goblin","Dark Elf","Titan")

RPG_DEMO_RACES = ("Human","Dwarf","Halfling","Elf")

RPG_SEXES = ["Male","Female","Neuter"]

RPG_CRAFT_SKILLS = ("Weapon Craft", "Armor Craft", "Alchemy", "Archery", "Poisons", "Enchanting", "Disenchanting", "Cooking", "Brewing", "Blacksmithing", "Scribing", "Research")


durSecond = 6
durMinute = durSecond * 60
durHour = durMinute * 60


RPG_ENCOUNTER_PVE = 0
RPG_ENCOUNTER_RVR = 1
RPG_ENCOUNTER_GVG = 2
RPG_ENCOUNTER_PVP = 3
RPG_ENCOUNTER_SETTINGS = {
    'PvE': RPG_ENCOUNTER_PVE,
    'RvR': RPG_ENCOUNTER_RVR,
    'GvG': RPG_ENCOUNTER_GVG,
    'PvP': RPG_ENCOUNTER_PVP
}
RPG_ENCOUNTER_SETTING_FORINDEX = {
    RPG_ENCOUNTER_PVE: 'PvE',
    RPG_ENCOUNTER_RVR: 'RvR',
    RPG_ENCOUNTER_GVG: 'GvG',
    RPG_ENCOUNTER_PVP: 'PvP'
}


RPG_MULTICLASS_SECONDARY_LEVEL_REQUIREMENT = 5
RPG_MULTICLASS_TERTIARY_LEVEL_REQUIREMENT  = 15

RPG_DEMO_PLEVEL_LIMIT = 15
RPG_DEMO_SLEVEL_LIMIT = 5

RPG_PRIVATE_VAULT_LIMIT = 300

RPG_ROMAN = ("I","II","III","IV","V","VI","VII","VIII","IX","X")

## @} # End defines group.
