// Torque Input Map File
moveMap.delete();
new ActionMap(moveMap);
moveMap.bindCmd(keyboard, "escape", "", "escapeFromGame();");
moveMap.bind(keyboard, "ctrl f5", toggleParticleEditor);
moveMap.bind(keyboard, "a", moveleft);
moveMap.bind(keyboard, "d", moveright);
moveMap.bind(keyboard, "w", moveforward);
moveMap.bind(keyboard, "s", movebackward);
moveMap.bind(keyboard, "space", jump);
moveMap.bind(keyboard, "r", setZoomFOV);
moveMap.bind(keyboard, "e", toggleZoom);
moveMap.bind(keyboard, "z", toggleFreeLook);
moveMap.bind(keyboard, "alt c", toggleCamera);
moveMap.bindCmd(keyboard, "ctrl w", "commandToServer(\'playCel\',\"wave\");", "");
moveMap.bindCmd(keyboard, "ctrl s", "commandToServer(\'playCel\',\"salute\");", "");
moveMap.bindCmd(keyboard, "ctrl k", "commandToServer(\'suicide\');", "");
moveMap.bindCmd(keyboard, "h", "commandToServer(\'use\',\"HealthKit\");", "");
moveMap.bindCmd(keyboard, "f1", "MACROWND_CHAR0.performClick();", "");
moveMap.bindCmd(keyboard, "f2", "MACROWND_CHAR1.performClick();", "");
moveMap.bindCmd(keyboard, "f3", "MACROWND_CHAR2.performClick();", "");
moveMap.bindCmd(keyboard, "f4", "MACROWND_CHAR3.performClick();", "");
moveMap.bindCmd(keyboard, "f5", "MACROWND_CHAR4.performClick();", "");
moveMap.bindCmd(keyboard, "f6", "MACROWND_CHAR5.performClick();", "");
moveMap.bindCmd(keyboard, "shift f1", "Py::CharSetTarget(0);", "");
moveMap.bindCmd(keyboard, "shift f2", "Py::CharSetTarget(1);", "");
moveMap.bindCmd(keyboard, "shift f3", "Py::CharSetTarget(2);", "");
moveMap.bindCmd(keyboard, "shift f4", "Py::CharSetTarget(3);", "");
moveMap.bindCmd(keyboard, "shift f5", "Py::CharSetTarget(4);", "");
moveMap.bindCmd(keyboard, "shift f6", "Py::CharSetTarget(5);", "");
moveMap.bindCmd(keyboard, "1", "MACROWND_MACRO0.performClick();", "");
moveMap.bindCmd(keyboard, "2", "MACROWND_MACRO1.performClick();", "");
moveMap.bindCmd(keyboard, "3", "MACROWND_MACRO2.performClick();", "");
moveMap.bindCmd(keyboard, "4", "MACROWND_MACRO3.performClick();", "");
moveMap.bindCmd(keyboard, "5", "MACROWND_MACRO4.performClick();", "");
moveMap.bindCmd(keyboard, "6", "MACROWND_MACRO5.performClick();", "");
moveMap.bindCmd(keyboard, "7", "MACROWND_MACRO6.performClick();", "");
moveMap.bindCmd(keyboard, "8", "MACROWND_MACRO7.performClick();", "");
moveMap.bindCmd(keyboard, "9", "MACROWND_MACRO8.performClick();", "");
moveMap.bindCmd(keyboard, "0", "MACROWND_MACRO9.performClick();", "");
moveMap.bindCmd(keyboard, "numpad1", "MACROWND_MACRO0.performClick();", "");
moveMap.bindCmd(keyboard, "numpad2", "MACROWND_MACRO1.performClick();", "");
moveMap.bindCmd(keyboard, "numpad3", "MACROWND_MACRO2.performClick();", "");
moveMap.bindCmd(keyboard, "numpad4", "MACROWND_MACRO3.performClick();", "");
moveMap.bindCmd(keyboard, "numpad5", "MACROWND_MACRO4.performClick();", "");
moveMap.bindCmd(keyboard, "numpad6", "MACROWND_MACRO5.performClick();", "");
moveMap.bindCmd(keyboard, "numpad7", "MACROWND_MACRO6.performClick();", "");
moveMap.bindCmd(keyboard, "numpad8", "MACROWND_MACRO7.performClick();", "");
moveMap.bindCmd(keyboard, "numpad9", "MACROWND_MACRO8.performClick();", "");
moveMap.bindCmd(keyboard, "numpad0", "MACROWND_MACRO9.performClick();", "");
moveMap.bindCmd(keyboard, "f", "Py::DoCommand(\"/INTERACT\");", "");
moveMap.bind(keyboard, "ctrl o", bringUpOptions);
moveMap.bindCmd(keyboard, "n", "NetGraph::toggleNetGraph();", "");
moveMap.bind(keyboard, "slash", TomeToggleSlash);
moveMap.bind(keyboard, "return", TomeToggleEnter);
moveMap.bind(keyboard, "tab", ToggleMouseLook );
moveMap.bind(mouse0, "xaxis", yaw);
moveMap.bind(mouse0, "yaxis", pitch);
moveMap.bind(mouse0, "button0", mouseFire);
moveMap.bind(keyboard, "ctrl 1", InputSetMacroPage1);
moveMap.bind(keyboard, "ctrl 2", InputSetMacroPage2);
moveMap.bind(keyboard, "ctrl 3", InputSetMacroPage3);
moveMap.bind(keyboard, "ctrl 4", InputSetMacroPage4);
moveMap.bind(keyboard, "ctrl 5", InputSetMacroPage5);
moveMap.bind(keyboard, "ctrl 6", InputSetMacroPage6);
moveMap.bind(keyboard, "ctrl 7", InputSetMacroPage7);
moveMap.bind(keyboard, "ctrl 8", InputSetMacroPage7);
moveMap.bind(keyboard, "ctrl 9", InputSetMacroPage7);
moveMap.bind(keyboard, "ctrl 0", InputSetMacroPage10);
