# Copyright (C) 2004-2007 Prairie Games, Inc
# Please see LICENSE.TXT for details

#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Sat Jan 22 12:01:43 2005

import wx

class MasterLoginDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MasterLoginDlg.__init__
        kwds["style"] = wx.CAPTION
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_3 = wx.Panel(self, -1, style=wx.STATIC_BORDER|wx.TAB_TRAVERSAL)
        self.label_3_copy = wx.StaticText(self.panel_3, -1, "Public Name:")
        self.publicNameTextCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.label_4_copy = wx.StaticText(self.panel_3, -1, "Password:")
        self.passwordTextCtrl = wx.TextCtrl(self.panel_3, -1, "", style=wx.TE_PASSWORD)
        self.loginBtn = wx.Button(self.panel_3, wx.ID_OK, "Login")
        self.cancelBtn = wx.Button(self.panel_3, wx.ID_CANCEL, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MasterLoginDlg.__set_properties
        self.SetTitle("Master Login")
        self.publicNameTextCtrl.SetSize((200, -1))
        self.passwordTextCtrl.SetSize((200, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MasterLoginDlg.__do_layout
        masterSizer = wx.BoxSizer(wx.HORIZONTAL)
        masterPanelSizer = wx.FlexGridSizer(2, 1, 0, 0)
        buttons = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2_copy = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_2_copy.Add(self.label_3_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.FIXED_MINSIZE, 8)
        grid_sizer_2_copy.Add(self.publicNameTextCtrl, 0, wx.ALL|wx.FIXED_MINSIZE, 8)
        grid_sizer_2_copy.Add(self.label_4_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.FIXED_MINSIZE, 8)
        grid_sizer_2_copy.Add(self.passwordTextCtrl, 0, wx.ALL|wx.FIXED_MINSIZE, 8)
        masterPanelSizer.Add(grid_sizer_2_copy, 1, wx.TOP|wx.ALIGN_CENTER_HORIZONTAL, 8)
        buttons.Add(self.loginBtn, 0, wx.ALL|wx.FIXED_MINSIZE, 16)
        buttons.Add(self.cancelBtn, 0, wx.ALL|wx.FIXED_MINSIZE, 16)
        masterPanelSizer.Add(buttons, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.panel_3.SetAutoLayout(True)
        self.panel_3.SetSizer(masterPanelSizer)
        masterPanelSizer.Fit(self.panel_3)
        masterPanelSizer.SetSizeHints(self.panel_3)
        masterSizer.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(masterSizer)
        masterSizer.Fit(self)
        masterSizer.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class MasterLoginDlg


