# Copyright (C) 2004-2007 Prairie Games, Inc
# Please see LICENSE.TXT for details


        
#WORLD SERVER CONFIGURATION 

WORLDTEXT = "Starter MMORPG"

STATICZONES = [
"base","landone","landtwo"
]

DYNAMICZONETIMEOUT = 10
WORLDPORT = 2006
ZONESTARTPORT = 29000

#UNSUPPORTED
MAXDYNAMICZONES = -1
MAXPLAYERS = -1
ALLOWGUESTS = False

PLAYERPASSWORD = ""
ZONEPASSWORD = ""

MOTD = "\\n"
