SERVER_PATCH_PREMIUM = "starter:mmo@http://127.0.0.1/svn/patchfiles"
SERVER_PATCH_DEMO = SERVER_PATCH_PREMIUM

SERVER_WORLD_USERNAME = "world"
SERVER_WORLD_PASSWORD = "world_password"
SERVER_DEFAULT_PORT = 2003

# Manhole
SERVER_MANHOLE_USERNAME = "manhole"
SERVER_MANHOLE_PASSWORD = "manhole_password"
SERVER_MANHOLE_PORT = 8192

# Character Server
SERVER_CSERVER_PASSWORD = "character_password"

# Support Email
SERVER_EMAIL_ADDRESS = ""
SERVER_EMAIL_ACCOUNT = ""
SERVER_EMAIL_PASSWORD = ""
SERVER_EMAIL_SERVER = ""
SERVER_EMAIL_PORT = 0

# MYSQL
SERVER_MYSQL_USER = ""
SERVER_MYSQL_PASSWORD = ""

DO_LAN_SERVER_FIX=True

RPG_SECURE_REGISTRATION=False
